version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    volumes: 
      - .:/app
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py","runserver", "0.0.0.0:80"]
    ports:
      - 8080:80
    depends_on:
      - db