version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    volumes: 
      - .:/app
    command: python manage.py runserver 0.0.0.0:80
    restart: always
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_started