# Generated by Django 3.0.5 on 2020-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='priceavailablity',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='profileskills',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='uid',
            field=models.CharField(default='053871c76de84333a89616126863abab',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False),
        ),
    ]
