# Generated by Django 3.0.5 on 2020-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200420_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='priceavailablity',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='profileskills',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='uid',
            field=models.UUIDField(default='c4c34c5898b24e008dccfd3afe9bd5d5',
                                   primary_key=True,
                                   serialize=False),
        ),
    ]
