# Generated by Django 3.0.5 on 2020-04-28 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='priceavailablity',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='profileskills',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False),
        ),
    ]
