# Generated by Django 3.0.5 on 2020-04-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200428_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isNotify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isVerify',
            field=models.BooleanField(default=False),
        ),
    ]
