# Generated by Django 3.0.5 on 2020-04-30 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200428_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid',
                 models.UUIDField(default=uuid.uuid4,
                                  primary_key=True,
                                  serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deviceId', models.CharField(max_length=100)),
                ('deviceType', models.CharField(max_length=100)),
                ('userType', models.IntegerField()),
                ('deviceToken', models.TextField()),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
