# Generated by Django 3.0.5 on 2020-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='EB', max_length=255),
            preserve_default=False,
        ),
    ]
